### ISSUE TITLE
fighting bugs

### ISSUE THREAD

**Issue by daigia99xx** [AlexKrutoy/PixelTapBot#10]
fighting bugs
![image](https://github.com/AlexKrutoy/PixelTapBot/assets/172129740/e612ad6a-2ec6-4233-aa3e-d59855f2daf7)

**Comment by ZeroParadoxHome** [comment]
Also the fight results usually is lose more than 85 percent of situations

**Comment by mrdarkerr** [comment]
same

**Comment by ButCheR-PRO** [comment]
same errors.  And it's impossible to put together a combo
