### ISSUE TITLE
[BAN] 102 - Unknown error during Authorization: Telegram says: [400 YOU_BLOCKED_USER] 

### ISSUE THREAD

**Issue by ButCheR-PRO** [AlexKrutoy/PixelTapBot#11]
`ERROR    | 102 - gamer | Unknown error during Authorization: Telegram says: [400 YOU_BLOCKED_USER] - You blocked this user (caused by "messages.RequestWebView")`
Меня забанили в игре?

**Comment by ChernikovM** [comment]
You are banned in tg

**Comment by pythonman999** [comment]
> `ERROR | 102 - gamer | Unknown error during Authorization: Telegram says: [400 YOU_BLOCKED_USER] - You blocked this user (caused by "messages.RequestWebView")` Меня забанили в игре?

Ты заблокировал бота скорее всего
