### ISSUE TITLE
Doesn't battle anymore

### ISSUE THREAD

**Issue by akumaburn** [AlexKrutoy/PixelTapBot#15]
Not sure but I think shortly after banning desktop clients they changed their API, it no longer automatically battles for me.

**Comment by ButCheR-PRO** [comment]
Download latest version

**Comment by akumaburn** [comment]
@ButCheR-PRO This is with the latest commit, it stopped battling, is it working on your end?

**Comment by AlexKrutoy** [comment]
Can you give me a screenshot of problem?

**Comment by ArseniyK1** [comment]
> Можете ли вы дать мне скриншот проблемы?
![image](https://github.com/AlexKrutoy/PixelTapBot/assets/109418393/31c14d84-29e8-4b7d-b3ed-946c0ea1c901)

**Comment by AlexKrutoy** [comment]
> > Можете ли вы дать мне скриншот проблемы?
> > ![image](https://private-user-images.githubusercontent.com/109418393/345768932-31c14d84-29e8-4b7d-b3ed-946c0ea1c901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMjgxNTIsIm5iZiI6MTcyMDEyNzg1MiwicGF0aCI6Ii8xMDk0MTgzOTMvMzQ1NzY4OTMyLTMxYzE0ZDg0LTI5ZTgtNGI3ZC1iM2VkLTk0NmMwZWExYzkwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMTE3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTYyNjE0YjBlMzBmMmQ5YzQ1YTQyMjM3MjA4OWE0YWU0ZGVkYmNkNGY4MDAzOTI1ZTdjY2Q2NzU2ZWQyOWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lNo1K2sLWEOhYs6D6kacikgnykWIeh_eAJuYmWRxBMk)
> 
> он клеймит, но не сражается, на аккичах по 2-3 боя

зайди в чат, там поможем:

https://t.me/hidden_codding_chat

**Comment by akumaburn** [comment]
It works with the latest commits, please note that battling doesn't seem to be worth it anymore because the reward has been halved. It used be double the amount if you won vs if you lost, so unless you can guarantee a higher than 50% win rate, battling seems a waste.
