### ISSUE TITLE
error during battle

### ISSUE THREAD

**Issue by razak95** [AlexKrutoy/PixelTapBot#17]
ERROR    | 371 - Exception during battle: Cannot write to closing transport
![image](https://github.com/AlexKrutoy/PixelTapBot/assets/15963928/2d864027-fe42-4c85-8cc2-c44d7ed7d5a1)

**Comment by Nagendra9Kumar** [comment]
![image](https://github.com/AlexKrutoy/PixelTapBot/assets/144660650/d3ba6fb5-fd01-4161-979c-7994de7830bc)
i also having same issue

**Comment by AlexKrutoy** [comment]
This happens when you use proxy. Try to use other proxy services or run without them
