### ISSUE TITLE
Error when launching bot new config 

### ISSUE THREAD

**Issue by Wellynounet** [AlexKrutoy/PixelTapBot#18]
cant run the bot 
i have and error 
![image](https://github.com/AlexKrutoy/PixelTapBot/assets/88185485/516064ff-711e-494c-b499-d4e3ea1f01cb)

![image](https://github.com/AlexKrutoy/PixelTapBot/assets/88185485/3a224ad6-8102-45dc-adad-a2489d248cf0)

**Comment by AlexKrutoy** [comment]
use python 3.10
