### ISSUE TITLE
Redundant api calls  (Waiting for x seconds before continuing (required by "users.GetFullUser"))

### ISSUE THREAD

**Issue by asyv3n** [AlexKrutoy/PixelTapBot#3]
Issue: **Waiting for 8 seconds before continuing (required by "users.GetFullUser")**
Every time when task loop ends. Script requesting two telegram api requests like RequestWebView and GetFullUser here: https://github.com/AlexKrutoy/PixelTapBot/blob/5bb2c9993a67522fdca7e6ac4f85e51e2d9f7582/bot/core/tapper.py#L73
and here https://github.com/AlexKrutoy/PixelTapBot/blob/5bb2c9993a67522fdca7e6ac4f85e51e2d9f7582/bot/core/tapper.py#L86

Solution:
Get this data once and save it until web app sesion will be expired, and avoid call this requests every loop iteration.

**Comment by asyv3n** [comment]
a proof that get_me under the hood uses `users.GetFullUser`
https://github.com/pyrogram/pyrogram/blob/efac17198b5fcaec1c2628c4bba0c288a4d617d4/pyrogram/methods/users/get_me.py#L25-L44

**Comment by AlexKrutoy** [comment]
fixed
